export default [{
    id: 0,
    name: "foods",
    visibleForAll: true
}, {
    id: 1,
    name: "walls",
    place: true,
    limit: 40,
    visibleForAll: true
}, {
    id: 2,
    name: "spikes",
    place: true,
    limit: 25,
    visibleForAll: true
}, {
    id: 3,
    name: "mills",
    place: true,
    limit: 100,
    visibleForAll: true
}, {
    id: 4,
    name: "traps",
    place: true,
    limit: 15,
    visibleForAll: false
}, {
    id: 5,
    name: "boosts",
    place: true,
    limit: 20
}]