import groups from "./groups.js"

export default [{ // apple
    id: 0,
    group: groups[0],
    req: ["food", 20],
    consume: function(doer) {
        return doer.changeHealth(20)
    },
    scale: 22,
    holdOffset: 15
}, { // cookie
    id: 1,
    age: 2,
    group: groups[0],
    req: ["food", 35],
    consume: function(doer) {
        return doer.changeHealth(35)
    },
    scale: 27,
    holdOffset: 15
}, { // wall tier 1
    id: 2,
    buildID: 0,
    group: groups[1],
    req: ["wood", 15],
    health: 350,
    scale: 55,
    holdOffset: 27,
    placeOffset: -10,
    isItem: true,
    needsCells: 4,
    ignoreCollision: false
}, { // wall tier 2
    id: 3,
    buildID: 1,
    parentID: 2,
    group: groups[1],
    req: ["wood", 25],
    health: 500,
    scale: 55,
    holdOffset: 27,
    placeOffset: -10,
    isItem: true,
    needsCells: 4,
    ignoreCollision: false
}, { // wall tier 3
    id: 4,
    buildID: 2,
    parentID: 3,
    age: 2,
    group: groups[1],
    req: ["stone", 30],
    health: 700,
    scale: 57,
    holdOffset: 27,
    placeOffset: -10,
    isItem: true,
    colDiv: 1,
    needsCells: 4
}, { // spike tier 1
    id: 5,
    buildID: 3,
    group: groups[2],
    req: ["wood", 20, "stone", 5],
    health: 300,
    damage: 15,
    scale: 49,
    power: 90,
    spritePadding: -23,
    holdOffset: 12,
    placeOffset: -5,
    isItem: true,
    needsCells: 4,
    colDiv: .9,
    ignoreCollision: false,
    colDamage: true
}, { // spike tier 2
    id: 6,
    buildID: 4,
    parentID: 5,
    group: groups[2],
    req: ["wood", 30, "stone", 8],
    health: 450,
    damage: 25,
    power: 95,
    scale: 49,
    spritePadding: -23,
    holdOffset: 12,
    placeOffset: -5,
    isItem: true,
    needsCells: 4,
    colDiv: .9,
    ignoreCollision: false,
    colDamage: true
}, { // spike tier 3
    id: 7,
    buildID: 5,
    parentID: 6,
    age: 4,
    group: groups[2],
    req: ["wood", 15, "stone", 30],
    health: 550,
    damage: 35,
    power: 100,
    scale: 52,
    spritePadding: -23,
    holdOffset: 12,
    placeOffset: -5,
    isItem: true,
    needsCells: 4,
    colDiv: .9,
    ignoreCollision: false,
    colDamage: true
}, { // windmill tier 1
    id: 8,
    buildID: 6,
    group: groups[3],
    req: ["wood", 40, "stone", 10],
    health: 400,
    goldPerSecond: 1,
    spritePadding: 25,
    scale: 60,
    holdOffset: 30,
    placeOffset: 5,
    isItem: true,
    needsCells: 4,
    colDiv: 1,
}, { // windmill tier 2
    id: 9,
    buildID: 7,
    group: groups[3],
    req: ["wood", 30, "stone", 60],
    health: 550,
    goldPerSecond: 2,
    spritePadding: 25,
    scale: 60,
    holdOffset: 30,
    placeOffset: 5,
    isItem: true,
    needsCells: 4,
    colDiv: 1,
}, { // pit trap
    id: 10,
    buildID: 8,
    group: groups[4],
    req: ["wood", 25, "stone", 20],
    health: 400,
    scale: 60,
    holdOffset: 25,
    placeOffset: -10,
    isItem: true,
    ignoreCollision: true,
    isTrap: true,
    collisionMagnitude: -40
}, { // boost pad
    id: 11,
    buildID: 9,
    group: groups[5],
    req: ["wood", 15, "stone", 30],
    health: 300,
    scale: 60,
    holdOffset: 25,
    placeOffset: -10,
    isItem: true,
    ignoreCollision: true,
    isBoost: true,
    boostSpeed: .35,
    collisionMagnitude: -15
}]